export const BYOK_OPENROUTER_HEADER = 'x-openrouter-api-key'
export const BYOK_OPENROUTER_ENV_VAR = 'CODEBUFF_BYOK_OPENROUTER'

export const BYOK_ANTHROPIC_API_KEY_ENV_VAR = 'CODEBUFF_BYOK_ANTHROPIC_API_KEY'
export const BYOK_ANTHROPIC_BASE_URL_ENV_VAR = 'CODEBUFF_BYOK_ANTHROPIC_BASE_URL'
export const BYOK_ANTHROPIC_MODELS_ENV_VAR = 'CODEBUFF_BYOK_ANTHROPIC_MODELS'
export const BYOK_ANTHROPIC_REVIEWER_MODEL_ENV_VAR = 'CODEBUFF_BYOK_REVIEWER_MODEL_TIER'

export const BYOK_LOCAL_API_KEY = 'byok-local-mode'
